GOOGLE_API_KEY: 'AIzaSyDBu0E_x067mvWLpmOSdRsnhYL9euWiczk'
KAFKA_BOOTSTRAP_SERVERS: 'velomobile-01.srvs.cloudkafka.com:9094, velomobile-02.srvs.cloudkafka.com:9094' # ,velomobile-03.srvs.cloudkafka.com:9094
KAFKA_SASL_USERNAME: 'xz6befqu'
KAFKA_SASL_PASSWORD: 'ZnTqLiR0WxwLHX_jdiGChcbi4W-H9Mzd'
KAFKA_TOPIC_PREFIX: 'xz6befqu-'