# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa650d8d6546cc94e9b128399bf560e5c32303c1891e0aa5557b921c7b35edaa9cad71bf89ca466fe7d85cb5374c236b41ce9275847fdb6d853a491de9f5d22c

test:
  secret_key_base: 584bbcd0114a118d1a5abc16c26d3837f92e45df5c97021553a7a6f0d47ef12fd015f2f4e44b935bfaf894e02faca2c042522855daaa380cc079298dc09c9f4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
